theme: minima
title: "Research Homepage | Jongseo Lee"
description: "KyungHee University, Vision and Learning Lab | Computer Vision Researcher"

# Remove built-in menu since we are using a custom one
header_pages: []

# Social Links (Optional)
minima:
  skin: classic
  social_links:
    github: jong980812
    linkedin: jongseo-lee
    email: your-email@example.com