theme: minima
title: "Research Homepage | Jongseo Lee"
description: "KyungHee University, Vision and Learning Lab | Computer Vision Researcher"

# 네비게이션 메뉴 순서
header_pages:
  - index.md
  - publications.md
  - projects.md
  - cv.md
  - contact.md
  - news.md

# 스타일 설정 (Jekyll Minima 테마 커스터마이징)
minima:
  skin: classic
  social_links:
    github: jong980812
    linkedin: your-linkedin
    email: your-email@example.com
