theme: minima  # (Minima 테마를 계속 사용할 경우)
defaults:
  - scope:
      path: ""  # 모든 파일에 적용
      type: "pages"  
    values:
      layout: "default"
title: "Research Homepage | Jongseo Lee"
description: "KyungHee University, Vision and Learning Lab | Computer Vision Researcher"

# Remove built-in menu since we are using a custom one
header_pages: []

# Social Links (Optional)
minima:
  skin: classic
  social_links:
    github: https://github.com/jong980812
    linkedin: https://www.linkedin.com/in/jongseo-lee-a551ab244/
    email: jong980812@Khu.ac.kr